DROP DATABASE IF EXISTS registration;
CREATE DATABASE registration CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE registration;

CREATE TABLE users (
user_id INT NOT NULL AUTO_INCREMENT,
email VARCHAR(255) NOT NULL,
name VARCHAR(100) NOT NULL,
password_hash VARCHAR(255) NOT NULL,
registration_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (user_id),
UNIQUE (email)
);

CREATE TABLE todos (
todo_id INT NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL,
title VARCHAR(200) NOT NULL,
due_date DATE NULL,
is_done TINYINT(1) NOT NULL DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (todo_id),
CONSTRAINT uq_todos_user_title UNIQUE (user_id, title),
FOREIGN KEY (user_id) REFERENCES users(user_id)
);
